// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Student_Attendance_System.Migrations
{
    [DbContext(typeof(Student_Attendance_SystemContext))]
    [Migration("20240111090301_initial_without_logic")]
    partial class initial_without_logic
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Student_Attendance_System.Models.CoursesPicker", b =>
                {
                    b.Property<int>("CoursesPickerid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CoursesPickerid"), 1L, 1);

                    b.Property<string>("Courses")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Dashboardid")
                        .HasColumnType("int");

                    b.HasKey("CoursesPickerid");

                    b.HasIndex("Dashboardid");

                    b.ToTable("CoursesPicker");
                });

            modelBuilder.Entity("Student_Attendance_System.Models.Dashboard", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isPresent")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.ToTable("Dashboard");
                });

            modelBuilder.Entity("Student_Attendance_System.Models.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Login");
                });

            modelBuilder.Entity("Student_Attendance_System.Models.RegisterStudent", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("Course")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateEnrolled")
                        .HasColumnType("datetime2");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("RegisterStudent");
                });

            modelBuilder.Entity("Student_Attendance_System.Models.StudentNamePicker", b =>
                {
                    b.Property<int>("StudentNamePickerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentNamePickerID"), 1L, 1);

                    b.Property<int?>("Dashboardid")
                        .HasColumnType("int");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentNamePickerID");

                    b.HasIndex("Dashboardid");

                    b.ToTable("StudentNamePicker");
                });

            modelBuilder.Entity("Student_Attendance_System.Models.CoursesPicker", b =>
                {
                    b.HasOne("Student_Attendance_System.Models.Dashboard", null)
                        .WithMany("SelectCourses")
                        .HasForeignKey("Dashboardid");
                });

            modelBuilder.Entity("Student_Attendance_System.Models.StudentNamePicker", b =>
                {
                    b.HasOne("Student_Attendance_System.Models.Dashboard", null)
                        .WithMany("SelectStudent")
                        .HasForeignKey("Dashboardid");
                });

            modelBuilder.Entity("Student_Attendance_System.Models.Dashboard", b =>
                {
                    b.Navigation("SelectCourses");

                    b.Navigation("SelectStudent");
                });
#pragma warning restore 612, 618
        }
    }
}
